In [ ]:
Data Understanding

In [2]:
import pandas as pd
data=pd.read_csv("train.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
data.shape

(891, 12)

In [7]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 66.2+ KB

In [10]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [47]:
data['Age']=data['Age'].fillna(data['Age'].sum())
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [18]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [25]:
total_pass=len(data)
total_pass

891

In [26]:
data["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [27]:
data["Survived"].value_counts().rename({
    0: "Died",
    1: "Survived"
})

Survived
Died        549
Survived    342
Name: count, dtype: int64

In [31]:
data.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [33]:
data["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [34]:
data.groupby('Pclass')["Survived"].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [38]:
import numpy as np
age_data=np.array(data['Age'])
age_data

array([22.        , 38.        , 26.        , 35.        , 35.        ,
       29.69911765, 54.        ,  2.        , 27.        , 14.        ,
        4.        , 58.        , 20.        , 39.        , 14.        ,
       55.        ,  2.        , 29.69911765, 31.        , 29.69911765,
       35.        , 34.        , 15.        , 28.        ,  8.        ,
       38.        , 29.69911765, 19.        , 29.69911765, 29.69911765,
       40.        , 29.69911765, 29.69911765, 66.        , 28.        ,
       42.        , 29.69911765, 21.        , 18.        , 14.        ,
       40.        , 27.        , 29.69911765,  3.        , 19.        ,
       29.69911765, 29.69911765, 29.69911765, 29.69911765, 18.        ,
        7.        , 21.        , 49.        , 29.        , 65.        ,
       29.69911765, 21.        , 28.5       ,  5.        , 11.        ,
       22.        , 38.        , 45.        ,  4.        , 29.69911765,
       29.69911765, 29.        , 19.        , 17.        , 26.        ,
       32.        , 16.        , 21.        , 26.        , 32.        ,
       25.        , 29.69911765, 29.69911765,  0.83      , 30.        ,
       22.        , 29.        , 29.69911765, 28.        , 17.        ,
       33.        , 16.        , 29.69911765, 23.        , 24.        ,
       29.        , 20.        , 46.        , 26.        , 59.        ,
       29.69911765, 71.        , 23.        , 34.        , 34.        ,
       28.        , 29.69911765, 21.        , 33.        , 37.        ,
       28.        , 21.        , 29.69911765, 38.        , 29.69911765,
       47.        , 14.5       , 22.        , 20.        , 17.        ,
       21.        , 70.5       , 29.        , 24.        ,  2.        ,
       21.        , 29.69911765, 32.5       , 32.5       , 54.        ,
       12.        , 29.69911765, 24.        , 29.69911765, 45.        ,
       33.        , 20.        , 47.        , 29.        , 25.        ,
       23.        , 19.        , 37.        , 16.        , 24.        ,
       29.69911765, 22.        , 24.        , 19.        , 18.        ,
       19.        , 27.        ,  9.        , 36.5       , 42.        ,
       51.        , 22.        , 55.5       , 40.5       , 29.69911765,
       51.        , 16.        , 30.        , 29.69911765, 29.69911765,
       44.        , 40.        , 26.        , 17.        ,  1.        ,
        9.        , 29.69911765, 45.        , 29.69911765, 28.        ,
       61.        ,  4.        ,  1.        , 21.        , 56.        ,
       18.        , 29.69911765, 50.        , 30.        , 36.        ,
       29.69911765, 29.69911765,  9.        ,  1.        ,  4.        ,
       29.69911765, 29.69911765, 45.        , 40.        , 36.        ,
       32.        , 19.        , 19.        ,  3.        , 44.        ,
       58.        , 29.69911765, 42.        , 29.69911765, 24.        ,
       28.        , 29.69911765, 34.        , 45.5       , 18.        ,
        2.        , 32.        , 26.        , 16.        , 40.        ,
       24.        , 35.        , 22.        , 30.        , 29.69911765,
       31.        , 27.        , 42.        , 32.        , 30.        ,
       16.        , 27.        , 51.        , 29.69911765, 38.        ,
       22.        , 19.        , 20.5       , 18.        , 29.69911765,
       35.        , 29.        , 59.        ,  5.        , 24.        ,
       29.69911765, 44.        ,  8.        , 19.        , 33.        ,
       29.69911765, 29.69911765, 29.        , 22.        , 30.        ,
       44.        , 25.        , 24.        , 37.        , 54.        ,
       29.69911765, 29.        , 62.        , 30.        , 41.        ,
       29.        , 29.69911765, 30.        , 35.        , 50.        ,
       29.69911765,  3.        , 52.        , 40.        , 29.69911765,
       36.        , 16.        , 25.        , 58.        , 35.        ,
       29.69911765, 25.        , 41.        , 37.        , 29.69911765,
       63.        , 45.        , 29.69911765,  7.        , 35.        ,
       65.        , 28.        , 16.        , 19.        , 29.69911765,
       33.        , 30.        , 22.        , 42.        , 22.        ,
       26.        , 19.        , 36.        , 24.        , 24.        ,
       29.69911765, 23.5       ,  2.        , 29.69911765, 50.        ,
       29.69911765, 29.69911765, 19.        , 29.69911765, 29.69911765,
        0.92      , 29.69911765, 17.        , 30.        , 30.        ,
       24.        , 18.        , 26.        , 28.        , 43.        ,
       26.        , 24.        , 54.        , 31.        , 40.        ,
       22.        , 27.        , 30.        , 22.        , 29.69911765,
       36.        , 61.        , 36.        , 31.        , 16.        ,
       29.69911765, 45.5       , 38.        , 16.        , 29.69911765,
       29.69911765, 29.        , 41.        , 45.        , 45.        ,
        2.        , 24.        , 28.        , 25.        , 36.        ,
       24.        , 40.        , 29.69911765,  3.        , 42.        ,
       23.        , 29.69911765, 15.        , 25.        , 29.69911765,
       28.        , 22.        , 38.        , 29.69911765, 29.69911765,
       40.        , 29.        , 45.        , 35.        , 29.69911765,
       30.        , 60.        , 29.69911765, 29.69911765, 24.        ,
       25.        , 18.        , 19.        , 22.        ,  3.        ,
       29.69911765, 22.        , 27.        , 20.        , 19.        ,
       42.        ,  1.        , 32.        , 35.        , 29.69911765,
       18.        ,  1.        , 36.        , 29.69911765, 17.        ,
       36.        , 21.        , 28.        , 23.        , 24.        ,
       22.        , 31.        , 46.        , 23.        , 28.        ,
       39.        , 26.        , 21.        , 28.        , 20.        ,
       34.        , 51.        ,  3.        , 21.        , 29.69911765,
       29.69911765, 29.69911765, 33.        , 29.69911765, 44.        ,
       29.69911765, 34.        , 18.        , 30.        , 10.        ,
       29.69911765, 21.        , 29.        , 28.        , 18.        ,
       29.69911765, 28.        , 19.        , 29.69911765, 32.        ,
       28.        , 29.69911765, 42.        , 17.        , 50.        ,
       14.        , 21.        , 24.        , 64.        , 31.        ,
       45.        , 20.        , 25.        , 28.        , 29.69911765,
        4.        , 13.        , 34.        ,  5.        , 52.        ,
       36.        , 29.69911765, 30.        , 49.        , 29.69911765,
       29.        , 65.        , 29.69911765, 50.        , 29.69911765,
       48.        , 34.        , 47.        , 48.        , 29.69911765,
       38.        , 29.69911765, 56.        , 29.69911765,  0.75      ,
       29.69911765, 38.        , 33.        , 23.        , 22.        ,
       29.69911765, 34.        , 29.        , 22.        ,  2.        ,
        9.        , 29.69911765, 50.        , 63.        , 25.        ,
       29.69911765, 35.        , 58.        , 30.        ,  9.        ,
       29.69911765, 21.        , 55.        , 71.        , 21.        ,
       29.69911765, 54.        , 29.69911765, 25.        , 24.        ,
       17.        , 21.        , 29.69911765, 37.        , 16.        ,
       18.        , 33.        , 29.69911765, 28.        , 26.        ,
       29.        , 29.69911765, 36.        , 54.        , 24.        ,
       47.        , 34.        , 29.69911765, 36.        , 32.        ,
       30.        , 22.        , 29.69911765, 44.        , 29.69911765,
       40.5       , 50.        , 29.69911765, 39.        , 23.        ,
        2.        , 29.69911765, 17.        , 29.69911765, 30.        ,
        7.        , 45.        , 30.        , 29.69911765, 22.        ,
       36.        ,  9.        , 11.        , 32.        , 50.        ,
       64.        , 19.        , 29.69911765, 33.        ,  8.        ,
       17.        , 27.        , 29.69911765, 22.        , 22.        ,
       62.        , 48.        , 29.69911765, 39.        , 36.        ,
       29.69911765, 40.        , 28.        , 29.69911765, 29.69911765,
       24.        , 19.        , 29.        , 29.69911765, 32.        ,
       62.        , 53.        , 36.        , 29.69911765, 16.        ,
       19.        , 34.        , 39.        , 29.69911765, 32.        ,
       25.        , 39.        , 54.        , 36.        , 29.69911765,
       18.        , 47.        , 60.        , 22.        , 29.69911765,
       35.        , 52.        , 47.        , 29.69911765, 37.        ,
       36.        , 29.69911765, 49.        , 29.69911765, 49.        ,
       24.        , 29.69911765, 29.69911765, 44.        , 35.        ,
       36.        , 30.        , 27.        , 22.        , 40.        ,
       39.        , 29.69911765, 29.69911765, 29.69911765, 35.        ,
       24.        , 34.        , 26.        ,  4.        , 26.        ,
       27.        , 42.        , 20.        , 21.        , 21.        ,
       61.        , 57.        , 21.        , 26.        , 29.69911765,
       80.        , 51.        , 32.        , 29.69911765,  9.        ,
       28.        , 32.        , 31.        , 41.        , 29.69911765,
       20.        , 24.        ,  2.        , 29.69911765,  0.75      ,
       48.        , 19.        , 56.        , 29.69911765, 23.        ,
       29.69911765, 18.        , 21.        , 29.69911765, 18.        ,
       24.        , 29.69911765, 32.        , 23.        , 58.        ,
       50.        , 40.        , 47.        , 36.        , 20.        ,
       32.        , 25.        , 29.69911765, 43.        , 29.69911765,
       40.        , 31.        , 70.        , 31.        , 29.69911765,
       18.        , 24.5       , 18.        , 43.        , 36.        ,
       29.69911765, 27.        , 20.        , 14.        , 60.        ,
       25.        , 14.        , 19.        , 18.        , 15.        ,
       31.        ,  4.        , 29.69911765, 25.        , 60.        ,
       52.        , 44.        , 29.69911765, 49.        , 42.        ,
       18.        , 35.        , 18.        , 25.        , 26.        ,
       39.        , 45.        , 42.        , 22.        , 29.69911765,
       24.        , 29.69911765, 48.        , 29.        , 52.        ,
       19.        , 38.        , 27.        , 29.69911765, 33.        ,
        6.        , 17.        , 34.        , 50.        , 27.        ,
       20.        , 30.        , 29.69911765, 25.        , 25.        ,
       29.        , 11.        , 29.69911765, 23.        , 23.        ,
       28.5       , 48.        , 35.        , 29.69911765, 29.69911765,
       29.69911765, 36.        , 21.        , 24.        , 31.        ,
       70.        , 16.        , 30.        , 19.        , 31.        ,
        4.        ,  6.        , 33.        , 23.        , 48.        ,
        0.67      , 28.        , 18.        , 34.        , 33.        ,
       29.69911765, 41.        , 20.        , 36.        , 16.        ,
       51.        , 29.69911765, 30.5       , 29.69911765, 32.        ,
       24.        , 48.        , 57.        , 29.69911765, 54.        ,
       18.        , 29.69911765,  5.        , 29.69911765, 43.        ,
       13.        , 17.        , 29.        , 29.69911765, 25.        ,
       25.        , 18.        ,  8.        ,  1.        , 46.        ,
       29.69911765, 16.        , 29.69911765, 29.69911765, 25.        ,
       39.        , 49.        , 31.        , 30.        , 30.        ,
       34.        , 31.        , 11.        ,  0.42      , 27.        ,
       31.        , 39.        , 18.        , 39.        , 33.        ,
       26.        , 39.        , 35.        ,  6.        , 30.5       ,
       29.69911765, 23.        , 31.        , 43.        , 10.        ,
       52.        , 27.        , 38.        , 27.        ,  2.        ,
       29.69911765, 29.69911765,  1.        , 29.69911765, 62.        ,
       15.        ,  0.83      , 29.69911765, 23.        , 18.        ,
       39.        , 21.        , 29.69911765, 32.        , 29.69911765,
       20.        , 16.        , 30.        , 34.5       , 17.        ,
       42.        , 29.69911765, 35.        , 28.        , 29.69911765,
        4.        , 74.        ,  9.        , 16.        , 44.        ,
       18.        , 45.        , 51.        , 24.        , 29.69911765,
       41.        , 21.        , 48.        , 29.69911765, 24.        ,
       42.        , 27.        , 31.        , 29.69911765,  4.        ,
       26.        , 47.        , 33.        , 47.        , 28.        ,
       15.        , 20.        , 19.        , 29.69911765, 56.        ,
       25.        , 33.        , 22.        , 28.        , 25.        ,
       39.        , 27.        , 19.        , 29.69911765, 26.        ,
       32.        ])

In [40]:
np.shape(age_data)

(891,)

In [44]:
np.reshape(age_data,(891,1))

array([[22.        ],
       [38.        ],
       [26.        ],
       [35.        ],
       [35.        ],
       [29.69911765],
       [54.        ],
       [ 2.        ],
       [27.        ],
       [14.        ],
       [ 4.        ],
       [58.        ],
       [20.        ],
       [39.        ],
       [14.        ],
       [55.        ],
       [ 2.        ],
       [29.69911765],
       [31.        ],
       [29.69911765],
       [35.        ],
       [34.        ],
       [15.        ],
       [28.        ],
       [ 8.        ],
       [38.        ],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.69911765],
       [29.69911765],
       [66.        ],
       [28.        ],
       [42.        ],
       [29.69911765],
       [21.        ],
       [18.        ],
       [14.        ],
       [40.        ],
       [27.        ],
       [29.69911765],
       [ 3.        ],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [18.        ],
       [ 7.        ],
       [21.        ],
       [49.        ],
       [29.        ],
       [65.        ],
       [29.69911765],
       [21.        ],
       [28.5       ],
       [ 5.        ],
       [11.        ],
       [22.        ],
       [38.        ],
       [45.        ],
       [ 4.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [19.        ],
       [17.        ],
       [26.        ],
       [32.        ],
       [16.        ],
       [21.        ],
       [26.        ],
       [32.        ],
       [25.        ],
       [29.69911765],
       [29.69911765],
       [ 0.83      ],
       [30.        ],
       [22.        ],
       [29.        ],
       [29.69911765],
       [28.        ],
       [17.        ],
       [33.        ],
       [16.        ],
       [29.69911765],
       [23.        ],
       [24.        ],
       [29.        ],
       [20.        ],
       [46.        ],
       [26.        ],
       [59.        ],
       [29.69911765],
       [71.        ],
       [23.        ],
       [34.        ],
       [34.        ],
       [28.        ],
       [29.69911765],
       [21.        ],
       [33.        ],
       [37.        ],
       [28.        ],
       [21.        ],
       [29.69911765],
       [38.        ],
       [29.69911765],
       [47.        ],
       [14.5       ],
       [22.        ],
       [20.        ],
       [17.        ],
       [21.        ],
       [70.5       ],
       [29.        ],
       [24.        ],
       [ 2.        ],
       [21.        ],
       [29.69911765],
       [32.5       ],
       [32.5       ],
       [54.        ],
       [12.        ],
       [29.69911765],
       [24.        ],
       [29.69911765],
       [45.        ],
       [33.        ],
       [20.        ],
       [47.        ],
       [29.        ],
       [25.        ],
       [23.        ],
       [19.        ],
       [37.        ],
       [16.        ],
       [24.        ],
       [29.69911765],
       [22.        ],
       [24.        ],
       [19.        ],
       [18.        ],
       [19.        ],
       [27.        ],
       [ 9.        ],
       [36.5       ],
       [42.        ],
       [51.        ],
       [22.        ],
       [55.5       ],
       [40.5       ],
       [29.69911765],
       [51.        ],
       [16.        ],
       [30.        ],
       [29.69911765],
       [29.69911765],
       [44.        ],
       [40.        ],
       [26.        ],
       [17.        ],
       [ 1.        ],
       [ 9.        ],
       [29.69911765],
       [45.        ],
       [29.69911765],
       [28.        ],
       [61.        ],
       [ 4.        ],
       [ 1.        ],
       [21.        ],
       [56.        ],
       [18.        ],
       [29.69911765],
       [50.        ],
       [30.        ],
       [36.        ],
       [29.69911765],
       [29.69911765],
       [ 9.        ],
       [ 1.        ],
       [ 4.        ],
       [29.69911765],
       [29.69911765],
       [45.        ],
       [40.        ],
       [36.        ],
       [32.        ],
       [19.        ],
       [19.        ],
       [ 3.        ],
       [44.        ],
       [58.        ],
       [29.69911765],
       [42.        ],
       [29.69911765],
       [24.        ],
       [28.        ],
       [29.69911765],
       [34.        ],
       [45.5       ],
       [18.        ],
       [ 2.        ],
       [32.        ],
       [26.        ],
       [16.        ],
       [40.        ],
       [24.        ],
       [35.        ],
       [22.        ],
       [30.        ],
       [29.69911765],
       [31.        ],
       [27.        ],
       [42.        ],
       [32.        ],
       [30.        ],
       [16.        ],
       [27.        ],
       [51.        ],
       [29.69911765],
       [38.        ],
       [22.        ],
       [19.        ],
       [20.5       ],
       [18.        ],
       [29.69911765],
       [35.        ],
       [29.        ],
       [59.        ],
       [ 5.        ],
       [24.        ],
       [29.69911765],
       [44.        ],
       [ 8.        ],
       [19.        ],
       [33.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [22.        ],
       [30.        ],
       [44.        ],
       [25.        ],
       [24.        ],
       [37.        ],
       [54.        ],
       [29.69911765],
       [29.        ],
       [62.        ],
       [30.        ],
       [41.        ],
       [29.        ],
       [29.69911765],
       [30.        ],
       [35.        ],
       [50.        ],
       [29.69911765],
       [ 3.        ],
       [52.        ],
       [40.        ],
       [29.69911765],
       [36.        ],
       [16.        ],
       [25.        ],
       [58.        ],
       [35.        ],
       [29.69911765],
       [25.        ],
       [41.        ],
       [37.        ],
       [29.69911765],
       [63.        ],
       [45.        ],
       [29.69911765],
       [ 7.        ],
       [35.        ],
       [65.        ],
       [28.        ],
       [16.        ],
       [19.        ],
       [29.69911765],
       [33.        ],
       [30.        ],
       [22.        ],
       [42.        ],
       [22.        ],
       [26.        ],
       [19.        ],
       [36.        ],
       [24.        ],
       [24.        ],
       [29.69911765],
       [23.5       ],
       [ 2.        ],
       [29.69911765],
       [50.        ],
       [29.69911765],
       [29.69911765],
       [19.        ],
       [29.69911765],
       [29.69911765],
       [ 0.92      ],
       [29.69911765],
       [17.        ],
       [30.        ],
       [30.        ],
       [24.        ],
       [18.        ],
       [26.        ],
       [28.        ],
       [43.        ],
       [26.        ],
       [24.        ],
       [54.        ],
       [31.        ],
       [40.        ],
       [22.        ],
       [27.        ],
       [30.        ],
       [22.        ],
       [29.69911765],
       [36.        ],
       [61.        ],
       [36.        ],
       [31.        ],
       [16.        ],
       [29.69911765],
       [45.5       ],
       [38.        ],
       [16.        ],
       [29.69911765],
       [29.69911765],
       [29.        ],
       [41.        ],
       [45.        ],
       [45.        ],
       [ 2.        ],
       [24.        ],
       [28.        ],
       [25.        ],
       [36.        ],
       [24.        ],
       [40.        ],
       [29.69911765],
       [ 3.        ],
       [42.        ],
       [23.        ],
       [29.69911765],
       [15.        ],
       [25.        ],
       [29.69911765],
       [28.        ],
       [22.        ],
       [38.        ],
       [29.69911765],
       [29.69911765],
       [40.        ],
       [29.        ],
       [45.        ],
       [35.        ],
       [29.69911765],
       [30.        ],
       [60.        ],
       [29.69911765],
       [29.69911765],
       [24.        ],
       [25.        ],
       [18.        ],
       [19.        ],
       [22.        ],
       [ 3.        ],
       [29.69911765],
       [22.        ],
       [27.        ],
       [20.        ],
       [19.        ],
       [42.        ],
       [ 1.        ],
       [32.        ],
       [35.        ],
       [29.69911765],
       [18.        ],
       [ 1.        ],
       [36.        ],
       [29.69911765],
       [17.        ],
       [36.        ],
       [21.        ],
       [28.        ],
       [23.        ],
       [24.        ],
       [22.        ],
       [31.        ],
       [46.        ],
       [23.        ],
       [28.        ],
       [39.        ],
       [26.        ],
       [21.        ],
       [28.        ],
       [20.        ],
       [34.        ],
       [51.        ],
       [ 3.        ],
       [21.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [33.        ],
       [29.69911765],
       [44.        ],
       [29.69911765],
       [34.        ],
       [18.        ],
       [30.        ],
       [10.        ],
       [29.69911765],
       [21.        ],
       [29.        ],
       [28.        ],
       [18.        ],
       [29.69911765],
       [28.        ],
       [19.        ],
       [29.69911765],
       [32.        ],
       [28.        ],
       [29.69911765],
       [42.        ],
       [17.        ],
       [50.        ],
       [14.        ],
       [21.        ],
       [24.        ],
       [64.        ],
       [31.        ],
       [45.        ],
       [20.        ],
       [25.        ],
       [28.        ],
       [29.69911765],
       [ 4.        ],
       [13.        ],
       [34.        ],
       [ 5.        ],
       [52.        ],
       [36.        ],
       [29.69911765],
       [30.        ],
       [49.        ],
       [29.69911765],
       [29.        ],
       [65.        ],
       [29.69911765],
       [50.        ],
       [29.69911765],
       [48.        ],
       [34.        ],
       [47.        ],
       [48.        ],
       [29.69911765],
       [38.        ],
       [29.69911765],
       [56.        ],
       [29.69911765],
       [ 0.75      ],
       [29.69911765],
       [38.        ],
       [33.        ],
       [23.        ],
       [22.        ],
       [29.69911765],
       [34.        ],
       [29.        ],
       [22.        ],
       [ 2.        ],
       [ 9.        ],
       [29.69911765],
       [50.        ],
       [63.        ],
       [25.        ],
       [29.69911765],
       [35.        ],
       [58.        ],
       [30.        ],
       [ 9.        ],
       [29.69911765],
       [21.        ],
       [55.        ],
       [71.        ],
       [21.        ],
       [29.69911765],
       [54.        ],
       [29.69911765],
       [25.        ],
       [24.        ],
       [17.        ],
       [21.        ],
       [29.69911765],
       [37.        ],
       [16.        ],
       [18.        ],
       [33.        ],
       [29.69911765],
       [28.        ],
       [26.        ],
       [29.        ],
       [29.69911765],
       [36.        ],
       [54.        ],
       [24.        ],
       [47.        ],
       [34.        ],
       [29.69911765],
       [36.        ],
       [32.        ],
       [30.        ],
       [22.        ],
       [29.69911765],
       [44.        ],
       [29.69911765],
       [40.5       ],
       [50.        ],
       [29.69911765],
       [39.        ],
       [23.        ],
       [ 2.        ],
       [29.69911765],
       [17.        ],
       [29.69911765],
       [30.        ],
       [ 7.        ],
       [45.        ],
       [30.        ],
       [29.69911765],
       [22.        ],
       [36.        ],
       [ 9.        ],
       [11.        ],
       [32.        ],
       [50.        ],
       [64.        ],
       [19.        ],
       [29.69911765],
       [33.        ],
       [ 8.        ],
       [17.        ],
       [27.        ],
       [29.69911765],
       [22.        ],
       [22.        ],
       [62.        ],
       [48.        ],
       [29.69911765],
       [39.        ],
       [36.        ],
       [29.69911765],
       [40.        ],
       [28.        ],
       [29.69911765],
       [29.69911765],
       [24.        ],
       [19.        ],
       [29.        ],
       [29.69911765],
       [32.        ],
       [62.        ],
       [53.        ],
       [36.        ],
       [29.69911765],
       [16.        ],
       [19.        ],
       [34.        ],
       [39.        ],
       [29.69911765],
       [32.        ],
       [25.        ],
       [39.        ],
       [54.        ],
       [36.        ],
       [29.69911765],
       [18.        ],
       [47.        ],
       [60.        ],
       [22.        ],
       [29.69911765],
       [35.        ],
       [52.        ],
       [47.        ],
       [29.69911765],
       [37.        ],
       [36.        ],
       [29.69911765],
       [49.        ],
       [29.69911765],
       [49.        ],
       [24.        ],
       [29.69911765],
       [29.69911765],
       [44.        ],
       [35.        ],
       [36.        ],
       [30.        ],
       [27.        ],
       [22.        ],
       [40.        ],
       [39.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [35.        ],
       [24.        ],
       [34.        ],
       [26.        ],
       [ 4.        ],
       [26.        ],
       [27.        ],
       [42.        ],
       [20.        ],
       [21.        ],
       [21.        ],
       [61.        ],
       [57.        ],
       [21.        ],
       [26.        ],
       [29.69911765],
       [80.        ],
       [51.        ],
       [32.        ],
       [29.69911765],
       [ 9.        ],
       [28.        ],
       [32.        ],
       [31.        ],
       [41.        ],
       [29.69911765],
       [20.        ],
       [24.        ],
       [ 2.        ],
       [29.69911765],
       [ 0.75      ],
       [48.        ],
       [19.        ],
       [56.        ],
       [29.69911765],
       [23.        ],
       [29.69911765],
       [18.        ],
       [21.        ],
       [29.69911765],
       [18.        ],
       [24.        ],
       [29.69911765],
       [32.        ],
       [23.        ],
       [58.        ],
       [50.        ],
       [40.        ],
       [47.        ],
       [36.        ],
       [20.        ],
       [32.        ],
       [25.        ],
       [29.69911765],
       [43.        ],
       [29.69911765],
       [40.        ],
       [31.        ],
       [70.        ],
       [31.        ],
       [29.69911765],
       [18.        ],
       [24.5       ],
       [18.        ],
       [43.        ],
       [36.        ],
       [29.69911765],
       [27.        ],
       [20.        ],
       [14.        ],
       [60.        ],
       [25.        ],
       [14.        ],
       [19.        ],
       [18.        ],
       [15.        ],
       [31.        ],
       [ 4.        ],
       [29.69911765],
       [25.        ],
       [60.        ],
       [52.        ],
       [44.        ],
       [29.69911765],
       [49.        ],
       [42.        ],
       [18.        ],
       [35.        ],
       [18.        ],
       [25.        ],
       [26.        ],
       [39.        ],
       [45.        ],
       [42.        ],
       [22.        ],
       [29.69911765],
       [24.        ],
       [29.69911765],
       [48.        ],
       [29.        ],
       [52.        ],
       [19.        ],
       [38.        ],
       [27.        ],
       [29.69911765],
       [33.        ],
       [ 6.        ],
       [17.        ],
       [34.        ],
       [50.        ],
       [27.        ],
       [20.        ],
       [30.        ],
       [29.69911765],
       [25.        ],
       [25.        ],
       [29.        ],
       [11.        ],
       [29.69911765],
       [23.        ],
       [23.        ],
       [28.5       ],
       [48.        ],
       [35.        ],
       [29.69911765],
       [29.69911765],
       [29.69911765],
       [36.        ],
       [21.        ],
       [24.        ],
       [31.        ],
       [70.        ],
       [16.        ],
       [30.        ],
       [19.        ],
       [31.        ],
       [ 4.        ],
       [ 6.        ],
       [33.        ],
       [23.        ],
       [48.        ],
       [ 0.67      ],
       [28.        ],
       [18.        ],
       [34.        ],
       [33.        ],
       [29.69911765],
       [41.        ],
       [20.        ],
       [36.        ],
       [16.        ],
       [51.        ],
       [29.69911765],
       [30.5       ],
       [29.69911765],
       [32.        ],
       [24.        ],
       [48.        ],
       [57.        ],
       [29.69911765],
       [54.        ],
       [18.        ],
       [29.69911765],
       [ 5.        ],
       [29.69911765],
       [43.        ],
       [13.        ],
       [17.        ],
       [29.        ],
       [29.69911765],
       [25.        ],
       [25.        ],
       [18.        ],
       [ 8.        ],
       [ 1.        ],
       [46.        ],
       [29.69911765],
       [16.        ],
       [29.69911765],
       [29.69911765],
       [25.        ],
       [39.        ],
       [49.        ],
       [31.        ],
       [30.        ],
       [30.        ],
       [34.        ],
       [31.        ],
       [11.        ],
       [ 0.42      ],
       [27.        ],
       [31.        ],
       [39.        ],
       [18.        ],
       [39.        ],
       [33.        ],
       [26.        ],
       [39.        ],
       [35.        ],
       [ 6.        ],
       [30.5       ],
       [29.69911765],
       [23.        ],
       [31.        ],
       [43.        ],
       [10.        ],
       [52.        ],
       [27.        ],
       [38.        ],
       [27.        ],
       [ 2.        ],
       [29.69911765],
       [29.69911765],
       [ 1.        ],
       [29.69911765],
       [62.        ],
       [15.        ],
       [ 0.83      ],
       [29.69911765],
       [23.        ],
       [18.        ],
       [39.        ],
       [21.        ],
       [29.69911765],
       [32.        ],
       [29.69911765],
       [20.        ],
       [16.        ],
       [30.        ],
       [34.5       ],
       [17.        ],
       [42.        ],
       [29.69911765],
       [35.        ],
       [28.        ],
       [29.69911765],
       [ 4.        ],
       [74.        ],
       [ 9.        ],
       [16.        ],
       [44.        ],
       [18.        ],
       [45.        ],
       [51.        ],
       [24.        ],
       [29.69911765],
       [41.        ],
       [21.        ],
       [48.        ],
       [29.69911765],
       [24.        ],
       [42.        ],
       [27.        ],
       [31.        ],
       [29.69911765],
       [ 4.        ],
       [26.        ],
       [47.        ],
       [33.        ],
       [47.        ],
       [28.        ],
       [15.        ],
       [20.        ],
       [19.        ],
       [29.69911765],
       [56.        ],
       [25.        ],
       [33.        ],
       [22.        ],
       [28.        ],
       [25.        ],
       [39.        ],
       [27.        ],
       [19.        ],
       [29.69911765],
       [26.        ],
       [32.        ]])

In [45]:
np.mean(age_data)

np.float64(29.69911764705882)

In [48]:
np.min(age_data)

np.float64(0.42)

In [49]:
np.max(age_data)

np.float64(80.0)

In [53]:
data[data["Age"] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,Q
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,S
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,S
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,S

In [54]:
data[(data["Age"]>60) & (data['Sex']=="female")]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,NaN

In [55]:
data['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [56]:
data.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64